name: Process Lyricify Syllable Lyrics

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  process_lyrics:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install PyGithub

      - name: Process Lyrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 process_lyrics.py
